### ISSUE TITLE
Add a GitHub action to automate release creation

### ISSUE THREAD

**Issue by shubhendumadhukar** [fauxauldrich/camouflage#28]
**Is your feature request related to a problem? Please describe.**
Current process for creating a new GitHub release is to manually create a new tag from `main` branch and add the changelog to release which seems to be an inefficient way of creating releases.

**Describe the solution you'd like**
An automated GitHub Actions, which is triggered anytime a pull request to main is approved and merged, should create a new GitHub release with proper changelog and [SemVer](https://semver.org) versioning.

**Describe alternatives you've considered**
Manual.

**Additional context**
NA

**Comment by slayer321** [comment]
Hey, I'm new to open source and want to contribute to this project so can you guide me on how can I work on this issue?

**Comment by shubhendumadhukar** [comment]
Thank you @slayer321, for your interest.

If you are already aware of how GitHub Actions work. You can start by forking this repo and creating a `release.yaml` file in `.github/workflow` folder. The `release.yaml` file should contain triggers, conditions and steps to create a new release every time a pull request is merged to `main` branch. The versioning system we follow is SemVer.

If you are not aware of how GitHub Actions work, I would recommend reading up on the same. Following repos should be a great place to start.
- https://github.com/semantic-release/semantic-release
- https://github.com/K-Phoen/semver-release-action

Once you are ready, let me know, I'll assign this issue to you. Goodluck!

**Comment by slayer321** [comment]
Thank you @shubhendumadhukar  for replying.
I don't know about Github Actions but I will learn it from your given reference and come back to you.

**Comment by Vyvy-vi** [comment]
There's already an action that exists for this - https://github.com/TriPSs/conventional-changelog-action
You could also check out this workflow from Eddie's repo for changelogs- https://github.com/eddiejaoude/stargate/blob/main/.github/workflows/changelog.yml
