### ISSUE TITLE
camouflage init returns exit code 1

### ISSUE THREAD

**Issue by ankitanallana-livongo** [fauxauldrich/camouflage#87]
**Describe the bug**
`camouflage init` in an empty directory returns an exit code of 1 

**To Reproduce**
1. Make an empty directory
2. 
2. Initialize camouflage
```
$ camouflage init
$ echo $?
```
Exit code returned is 1. All directories are created correctly and without issue. But for some reason the exit code is 1.

**Expected behavior**
Exit Code should be 0 in the case of successful initialization

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Version: 0.5.8

**Additional context**
I'm trying to build a Docker image with camouflage installed. The final command is `camouflage init` which produces an exit code 1. Tried it on my computer and I see the same issue.

**Comment by ankitanallana-livongo** [comment]
@shubhendumadhukar many thanks for getting the fix in there! :) 

I'm not sure I understand syncing mock files between 2 containers? 🤔 

But, here's what I'm doing - I'm first building a base image with Camouflage already installed. After that, any microservice that requires Camouflage for their mocking requirements can build a second docker image on top of this base and set the folder structure/upload lock files accordingly - it's a very simple thing we're trying to do!

**Comment by shubhendumadhukar** [comment]
Understood. Thank you.

I was referring to the scenario where you might have more than one container deployed for the same microservice, and need to update a mock file without having to redeploy the containers.

Anyway, this might not be applicable for your use case (yet).
